### ISSUE TITLE
Please add more keyboard shortcuts

### ISSUE THREAD

**Issue by beavailable** [readest/readest#11]
It would be nice if I could go back/forward and exit the app (and do some other operations maybe) with keyboard shortcuts.

**Comment by beavailable** [comment]
> I like a vim-like keybinding just like the vimium in a browser.

Me too.

**Comment by chrox** [comment]
Close this now as implemented in #58 and #59. Checkout the full list of shortcuts here: https://github.com/readest/readest/wiki/Keyboard-Shortcuts-Reference-Guide.
