### ISSUE TITLE
Too little book information displayed on the book management page

### ISSUE THREAD

**Issue by wenmin92** [readest/readest#15]
## Bug Description

The file type, file name, file size, number of pages, author, date of publication, publisher, last read, reading time, adding time, etc. are missing from the book management page.
Unable to view valid information through the right-click menu.

**Example:**

One book is added in both formats, but it is impossible to distinguish between them from the management page.

## Expected behavior

- Show more basic information about the book directly on the admin page.
- View more information via context menu.

**Comment by BruceLee569** [comment]
Also suggest that you can choose to display the file name instead of the title in the book.

**Comment by chrox** [comment]
Yes the home library page now is still basic and unpolished. But it might not be the current priority for now before I implement the support for mobile platforms and synchronization across platform.

**Comment by BruceLee569** [comment]
> Yes the home library page now is still basic and unpolished. But it might not be the current priority for now before I implement the support for mobile platforms and synchronization across platform.

These two futures are also what users need most 🫡

**Comment by zangjiucheng** [comment]
Is the functionality of the mouse cover, which opens a card displaying more detailed information when pressed with the spacebar, working as intended?

**Comment by chrox** [comment]
> Is the functionality of the mouse cover, which opens a card displaying more detailed information when pressed with the spacebar, working as intended?

When implementing reading functionalities that are already present in the [foliate project](https://github.com/johnfactotum/foliate). It's better to refer to the UI/UE of the foliate project of that functionality. As this project is still largely a rewrite of foliate. And I wish to keep consistency of UI/UE between Readest and Foliate.
