### ISSUE TITLE
FR: support for side loaded fonts and system provided fonts

### ISSUE THREAD

**Issue by MrKyomoto** [readest/readest#31]
I don't find where I can apply my downloaded font.

And this is important for me cuz I'm a Chinese, my books are Chinese characters and clearly default fonts dont support this language :(

**Comment by chrox** [comment]
The browser should fallback to correct font when rendering the Chinese characters. Do you have any screenshots for failed rendering of Chinese text?

**Comment by MrKyomoto** [comment]
Sorry, my words are ambiguous. The web version works good while the app version doesn't. I can change the font in the browser but the app seems nowhere to change



---Original---
From: "Huang ***@***.***&gt;
Date: Mon, Dec 23, 2024 15:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chrox/readest] How can I add my downloaded font into the app?(Issue #31)




 
The browser should fallback to correct font when rendering the Chinese characters. Do you have any screenshots for failed rendering of Chinese text?

**Comment by chrox** [comment]
Any screenshots？And what's your operating system version and Readest version?

**Comment by MrKyomoto** [comment]
![image](https://github.com/user-attachments/assets/7ae06bef-9567-4366-9202-82fc300fb474)
Image 1 is the web version, as you can see the font is what I have set in my Chrome Browser

While the image 2 is the APP version, but the appearance is what it shows:
![image](https://github.com/user-attachments/assets/28bfdcfc-1944-4428-b81d-26c308c38f1b)
My question is that Readest seems dont support user's downloaded font right? What can I do to change the font in the app to what the web version shows?

**Comment by chrox** [comment]
Currently Readest only supports to customize builtin fonts, it’s a good feature request to support side loaded fonts though.

**Comment by MrKyomoto** [comment]
Okay, thanks a lot. Hope readest better day by day :)

**Comment by chrox** [comment]
![image](https://github.com/user-attachments/assets/13ce9730-c78a-470b-8aea-99fed5e361ab)

Now readest supports more system fonts. If your side loaded fonts are not present. You can add them to the custom CSS like this:

p {
  font-family: 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', 'SimSun', sans-serif !important;
}

**Comment by MrKyomoto** [comment]
That helps a lot :)

---Original---
From: "Huang ***@***.***&gt;
Date: Mon, Dec 23, 2024 15:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chrox/readest] How can I add my downloaded font into the app?(Issue #31)




 
Any screenshots？And what's your operating system version and Readest version?
