### ISSUE TITLE
FR: [ctrl+mouse wheel to zoom]

### ISSUE THREAD

**Issue by retsyo** [readest/readest#35]
Just as many appliactions do, let readest supporting zooming by ctrl+mouse wheel
As for me, ctrl + wheel down means to make the font smaller; but I met some app which think it should make font bigger. So maybe there is an option to choose 

Anthor choice is shortcut, for example, ctrl and plus(+) means to make font bigger

**Comment by chrox** [comment]
Close this now as implemented in #59. Checkout the full list of shortcuts here: https://github.com/readest/readest/wiki/Keyboard-Shortcuts-Reference-Guide.
