### ISSUE TITLE
Debian package missing "Section" field

### ISSUE THREAD

**Issue by beavailable** [readest/readest#38]
## Bug Description

The debian package of this software doesn't have "Section" field in its `control` file, which causes a problem. 

**Example:**

I'm trying to use `reprepro` to create a local apt repository for my daily use. If I use `reprepro` to add the deb file:
```bash
reprepro includedeb bookworm /path/to/package.deb
```
I get an error:
```
No section given for 'readest', skipping.
There have been errors!
```
Although I could use `--section` option like this:
```bash
reprepro --section text includedeb bookworm /path/to/package.deb
```
But if I want to add debs in a shell script for all debs, this is not gonna work, because I don't want all my debs have "text" section.

## Expected behavior

The package does have a "Section" field and I could add it with `reprepro` successfully.

**Comment by chrox** [comment]
This project uses [tauri-action](https://github.com/tauri-apps/tauri-action) to release packages for supported platforms. And I have little experience on the debian packaging system. Is there anywhere we can add the `Section` info?

**Comment by beavailable** [comment]
I'm not familiar with rust language and tauri, but I found this: https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-bundler/src/bundle/settings.rs#L196, I think you can use a `DebianSettings` to add it.
