### ISSUE TITLE
Please consider supporting this feature, When in the scrolling mode, if you scroll to the bottom of the page and scroll again, it will automatically switch to the next page.

### ISSUE THREAD

**Issue by rango886** [readest/readest#5]

**Comment by chrox** [comment]
Btw, you can also use the arrow key left/right ← / → to navigate to next chapter at the end of the current chapter in scrolled mode.

**Comment by rango886** [comment]
If it's like this, I'll have to switch back and forth between the mouse and the keyboard again and again. If mouse auto page turning is supported, then I can just use the mouse alone. In this way, I can lie down and read books while holding a wireless mouse.   :-)

**Comment by chrox** [comment]
Sounds fair enough. :D

**Comment by chrox** [comment]
But you can still use the single click on the right half of the page to navigate to the next chapter at the end of the current chapter in scrolled mode. I tested just now and it worked. :)

**Comment by chrox** [comment]
I'm not sure if keeping the boundary of chapters is useful for sometimes. When you scroll to the bottom and cannot scroll further it reminds you that it comes to the boundary of the chapter. And you need further action to go to the next chapter like a mouse click or key press.

**Comment by rango886** [comment]
I just tried it and found that I can click on any blank part without text to turn to the next page. This is really useful. Thank you.

**Comment by rango886** [comment]
I will imagine an EPUB book as a single page so that I can read it smoothly from top to bottom without a sense of fragmentation. Each title serves as an anchor for jumping, and there won't be any hitch. Whether it's at the beginning (scrolling up with the wheel takes you to the previous page) or at the end (scrolling down with the wheel takes you to the next page).

**Comment by rango886** [comment]
Perhaps a setting can be added to the software to set whether to remind when turning pages at the page boundary.

**Comment by citrus77** [comment]
With the latest build I've noticed it works now. Apparently only when the TOC is closed, but that's not a deal breaker to me. Thanks so much for implementing this!

**Comment by chrox** [comment]
> With the latest build I've noticed it works now. Apparently only when the TOC is closed, but that's not a deal breaker to me. Thanks so much for implementing this!

Thanks for your feedback.

**Comment by chrox** [comment]
Close this now as it's not planned.
