### ISSUE TITLE
FR: highlights on PDF without TOC should have page number as highlight text

### ISSUE THREAD

**Issue by chrox** [readest/readest#51]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently the highlight text is empty which makes the highlight on PDF without TOC unusable.

**Describe the solution you'd like**
Highlights on PDF without TOC should have page number as highlight text.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Annotator component to include the page number as highlight text for PDFs without a table of contents. This change ensures that highlights on PDFs without TOC are usable by providing context with the page number.

You can review changes in this commit: https://github.com/mark-addams001881/readest-readest-51/commit/c3f48682fadae052237792d55756e2ed7945cc7d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
