### ISSUE TITLE
Couldn't start since v0.8.5 on debian bookworm

### ISSUE THREAD

**Issue by beavailable** [readest/readest#60]
## Bug Description
Here's the error message when I start the app in a terminal:
```
Readest: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by Readest)
```
I think the problem is that newer versions of Readest were built on a system that has a newer version of glibc than the version debian bookworm has provided (which is 2.36, see https://tracker.debian.org/pkg/glibc).

**Comment by chrox** [comment]
Thanks for your report. Yes it seems since version 0.8.5 GitHub action uses Ubuntu 24.04 by default to build Linux binaries prior to which Ubuntu 22.04 is used. I think it should be safe to still use 22.04 and solve this issue.

**Comment by chrox** [comment]
See: https://github.com/actions/runner-images/issues/10636

Switched back to `ubuntu-22.04` to build Linux binaries. And the binaries are re-uploaded. Could you try if it works?

**Comment by beavailable** [comment]
It works now, thanks for fixing this!
