### ISSUE TITLE
FR: It might be better to change the binary filename from `Readest` to `readest`

### ISSUE THREAD

**Issue by beavailable** [readest/readest#61]
In linux, binary filenames are usually all lowercase and it's easier to use than first-letter-uppercase commands from terminal, I think it's a good idea to make the chagne.

However, I don't know if there's any difference between those names in other platforms, so I'm just putting it here for discussion, different opinions are welcome.

**Comment by chrox** [comment]
I don't use Linux much now. Most of my works are done on macOS. But does Readest can be accessed from cli in Linux? If it's possible to run Readest from terminal it's quite reasonable to change the name to `readest`.

**Comment by chrox** [comment]
Can you elaborate on how do you use it on Linux? Do you have any interest to add Readest to popular Linux distributions?

**Comment by beavailable** [comment]
> But does Readest can be accessed from cli in Linux?

Of course it does, the binary file is located in `/usr/bin` directory which is in `PATH` environment variable.

> Can you elaborate on how do you use it on Linux?

I guess you're asking why but not how? Usually for debugging purpose such as https://github.com/readest/readest/issues/60

> Do you have any interest to add Readest to popular Linux distributions?

I'd like to. Unfortunately I haven't learned how so far.

**Comment by chrox** [comment]
> > But does Readest can be accessed from cli in Linux?
> 
> Of course it does, the binary file is located in `/usr/bin` directory which is in `PATH` environment variable.
> 
> > Can you elaborate on how do you use it on Linux?
> 
> I guess you're asking why but not how? Usually for debugging purpose such as #60
> 

That will be great to have the binary in the system `path` by default. I thought it might require the users to copy some staff around to make it accessible in terminal.

**Comment by chrox** [comment]
Changed in commit [Rename binary execuable to readest for better cli interface](https://github.com/readest/readest/commit/b8af4832295e1e90e04235475b0fe1ee47be946c).

**Comment by beavailable** [comment]
Actually, you could change the binary filename without affecting the name in `Cargo.toml` (I don't know if it's the application name) by adding the `mainBinaryName` property in `apps/readest-app/src-tauri/tauri.conf.json`, see https://v2.tauri.app/reference/config/#mainbinaryname

**Comment by chrox** [comment]
Good catch. Thanks.
